plugins {
    id 'java'
    id 'application'
}

group = 'com.manning.junitbook'
archivesBaseName = 'spring'
version = '1.0-SNAPSHOT'

sourceCompatibility = '17'
targetCompatibility = '17'

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

repositories {
    // 중앙 저장소로 mavenCentral를 사용
    // 어떤 저장소든지 등록 가능
    mavenCentral()
}

dependencies {
    // Spring framework
    implementation 'org.springframework:spring-context:6.2.1'
    testImplementation 'org.springframework:spring-test:6.2.1'

    // JUnit Jupiter API
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
    // JUnit Jupiter Engine
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
}

test {
    useJUnitPlatform()
}
