plugins {
    id 'java'
}

group = 'com.manning.junitbook'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.1'
    // JUnit Jupiter API
    testImplementation 'org.junit.jupiter:junit-jupiter-api:6.1.1'
    // JUnit Jupiter Engine
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.1.1'
}

test {
    useJUnitPlatform()
}
